= Chromium B.S.U.
:toc:
:sectnums:
ifndef::env-github[:icons: font]
:note-caption: :paperclip:
:important-caption: :exclamation:
:warning-caption: :warning:

[IMPORTANT]
====
The commit history of this branch is volatile. +
Rebasing and force pushing happens at will. +
The commits in this branch mostly collect changes with a narrow scope. +
They rarely document code evolution. +
The history may be rewritten without notice.
====

== Chromium B.S.U.

https://sourceforge.net/projects/chromium-bsu/

https://en.wikipedia.org/wiki/Chromium_B.S.U.

Fork::
https://github.com/hghpublic/chromium-bsu

== Build & Run in Devcontainer

TBD

== Dependencies

Graphics::        
OpenGL and GLU (mesa for e.g.)

Window & input::
. SDL 1.1.6 or greater
. GLUT is an alternative

Sound::           
. OpenAL and ALUT
. SDL Mixer is an alternative

Image loading::
. glpng
. SDL_image is an alternative but has rendering issues

Text rendering::
. GLC (QuesoGLC for e.g.)
. FTGL 2.1.3 or greater is an alternative

Font::            
. Gothic Uralic bold recommended
. any TrueType font is an alternative

=== freeglut

https://github.com/freeglut/freeglut

https://freeglut.sourceforge.net/

=== glpng

James Le Cuirot

OpenGL PNG image library

https://repo.or.cz/glpng.git

git://repo.or.cz/glpng.git


=== QuesoGLC

https://quesoglc.sourceforge.io/


https://sourceforge.net/projects/quesoglc/

git clone https://git.code.sf.net/p/quesoglc/code quesoglc-code


=== FTGL

https://github.com/frankheckenbach/ftgl

https://sourceforge.net/projects/ftgl/

https://github.com/cdave1/ftgles


== Fonts

Gothic Uralic bold::
[source, shell]
----
❯ sudo apt install fonts-uralic

❯ find /usr/share/fonts -type f -name "gothu*.ttf" 
/usr/share/fonts/truetype/uralic/gothu___.ttf
/usr/share/fonts/truetype/uralic/gothub__.ttf
----

== Todos

. Clean up Dockerfile.
.. Remove unneeded packages.
.. Combine `deps` layers.

. Fix defines.
.. `-DLOCALEDIR`
.. `-DPKGDATADIR`

. Fix localization support.
